#!/usr/bin/env python3
"""VERIFY every article cover is genuinely generated by Pollinations AI.

Checks every jpg in static/images/ against the Pollinations signature:
  - EXIF Make == "sana" (the Pollinations model that generated it)
  - exactly 800x450 (Pollinations requested size)

Usage:
  python scripts/verify_images.py          # scan static/images/*.jpg
  python scripts/verify_images.py --strict # also check every post's frontmatter

Exit code 0 = all verified. Exit code 1 = at least one image is NOT
Pollinations-generated (report printed). Safe to run anywhere (no network).
"""
import hashlib
import re
import sys
from pathlib import Path

try:
    from PIL import Image
    from PIL.ExifTags import TAGS
except ImportError:
    print("ERROR: Pillow required — run: pip install Pillow")
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
IMG_DIR = ROOT / "static" / "images"


def is_pollinations(path: Path) -> bool:
    try:
        with Image.open(path) as im:
            if im.format != "JPEG":
                return False
            w, h = im.size
            if w != 800 or h != 450:
                return False
            exif = im._getexif()
            if not exif:
                return False
            for k, v in exif.items():
                if TAGS.get(k) == "Make" and str(v).strip().lower() == "sana":
                    return True
            return False
    except Exception:
        return False


def main():
    strict = "--strict" in sys.argv
    jpgs = sorted(IMG_DIR.glob("*.jpg"))
    if not jpgs:
        print("No covers found in static/images/")
        return 0

    ok, bad = [], []
    for jpg in jpgs:
        (ok if is_pollinations(jpg) else bad).append(jpg.name)

    print(f"Scanned {len(jpgs)} covers in static/images/\n")
    for name in ok:
        print(f"  ✔ POLLINATIONS  {name}")
    for name in bad:
        print(f"  ✘ NOT-POLLINATIONS  {name}")

    if strict:
        import re
        posts = sorted((ROOT / "content" / "posts").glob("*.md"))
        missing = []
        for p in posts:
            body = p.read_text(encoding="utf-8")
            m = re.search(r"(?m)^image:\s*\"?([^\n\"]+)\"?\s*$", body)
            img = m.group(1).strip() if m else ""
            if not img:
                missing.append(f"{p.name}: (no image)")
                continue
            rel = img.removeprefix("/images/").split("?")[0]
            if not (IMG_DIR / rel).exists():
                missing.append(f"{p.name}: {img}")
        print("\n-- strict: posts without a local cover --")
        for x in missing:
            print("  ", x)

        # Duplicate-image detection: reject two posts sharing byte-identical cover.
        by_hash = {}
        for p in posts:
            body = p.read_text(encoding="utf-8")
            m = re.search(r"(?m)^image:\s*\"?([^\n\"]+)\"?\s*$", body)
            img = m.group(1).strip() if m else ""
            if not img or img.startswith("http"):
                continue
            rel = img.removeprefix("/images/").split("?")[0]
            jpg = IMG_DIR / rel
            if not jpg.exists():
                continue
            h = hashlib.sha256(jpg.read_bytes()).hexdigest()
            by_hash.setdefault(h, []).append(p.name)
        dup = {h: v for h, v in by_hash.items() if len(v) > 1}
        if dup:
            print("\n--strict: DUPLICATE covers shared by multiple posts --")
            for h, v in dup.items():
                print("   ", ", ".join(v))
            print("NON-UNIQUE IMAGES FOUND — every article must have a unique cover.")
            return 1

    print(f"\nRESULT: {len(ok)}/{len(jpgs)} Pollinations-verified")
    if bad:
        print("NON-POLLINATIONS IMAGES FOUND — every cover must be Pollinations.")
        return 1
    print("ALL COVERS ARE POLLINATIONS-GENERATED ✔")
    return 0


if __name__ == "__main__":
    sys.exit(main())